user_pref("browser.shell.checkDefaultBrowser", false)
user_pref("browser.startup.page", 3)
user_pref("browser.tabs.animate", false)
user_pref("browser.tabs.warnOnClose", false)
user_pref("extensions.findbartweak.onStartup", true)
user_pref("extensions.findbartweak.sightsCurrent", false)
user_pref("extensions.tabscroll.downScrollsLeft", false)
user_pref("extensions.treestyletab.autoAttach", false)
user_pref("extensions.treestyletab.autoCollapseExpandSubtreeOnAttach", false)
user_pref("extensions.treestyletab.tabbar.autoHide.mode.fullscreen", 0)
user_pref("extensions.treestyletab.tooltip.mode", 0)
user_pref("font.name.monospace.ja", "Myrica MM")
user_pref("font.name.monospace.x-western", "Myrica MM")
user_pref("font.name.sans-serif.ja", "Rounded-L Mgen+ 1c")
user_pref("font.name.sans-serif.x-western", "Rounded-L Mgen+ 1c")
user_pref("general.autoScroll", false)
user_pref("general.smoothScroll", false)
user_pref("general.warnOnAboutConfig", false)
user_pref("gfx.font_rendering.cleartype_params.enhanced_contrast", 100)
user_pref("gfx.font_rendering.cleartype_params.rendering_mode", 5)
user_pref("plugins.click_to_play", true)
user_pref("privacy.donottrackheader.enabled", true)
user_pref("startup.homepage_welcome_url", "https://rawgit.com/pomutemu/config/master/.firefox/main/install-trigger.html")
user_pref("ui.key.contentAccess", 4)
